version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 3001:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: secret
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: secret
